r1:
  hostname: 172.20.20.11
  groups:
    - ios          # dimensao: plataforma
    - edge         # dimensao: papel/role
  data:
    loopback_ip: 1.1.1.1
r2:
  hostname: 172.20.20.12
  groups:
    - ios
    - core
  data:
    loopback_ip: 10.255.0.2
r3:
  hostname: 172.20.20.13
  groups:
    - ios
    - edge
  data:
    loopback_ip: 10.255.0.3
r4:
  hostname: 172.20.20.14
  groups:
    - ios
    - core
  data:
    loopback_ip: 10.255.0.4
r5:
  hostname: 172.20.20.21
  groups:
    - eos
    - site_poa
    - edge
  data:
    loopback_ip: 10.255.0.21
