r1:
  hostname: 172.20.20.11
  groups:
    - ios          # dimensao: plataforma
    - site_poa     # dimensao: site
    - edge         # dimensao: papel
r2:
  hostname: 172.20.20.12
  groups:
    - ios
    - site_poa
    - core
r3:
  hostname: 172.20.20.13
  groups:
    - ios
    - site_gru
    - edge
r4:
  hostname: 172.20.20.14
  groups:
    - ios
    - site_gru
    - core
eos1:
  hostname: 172.20.20.21
  groups:
    - eos
    - site_poa
    - edge
eos2:
  hostname: 172.20.20.22
  groups:
    - eos
    - site_gru
    - edge
f5:
  hostname: 172.20.20.31
  groups:
    - f5
    - site_poa
    - lb
