query DeviceConfig($device: String!) {
  DcimDevice(name__value: $device) {
    edges {
      node {
        name { value }
        platform {
          node {
            nornir_platform { value }
            netmiko_device_type { value }
          }
        }
        primary_address {
          node { address { value } }
        }
        interfaces {
          edges {
            node {
              name { value }
              description { value }
              ... on InterfacePhysical {
                mtu { value }
                ip_addresses {
                  edges { node { address { value } } }
                }
              }
            }
          }
        }
      }
    }
  }
}
